#!/usr/bin/env python3
"""
Test a new e-nose CSV with the models generated by
food_freshness_multitask.py.

Run directly in PyCharm.

Expected project structure
--------------------------
your_project/
├── food_freshness_multitask.py
├── test_model.py
├── enose_test.csv
└── classification_outputs/
    ├── dataset_and_preprocessing_metadata.json
    └── models/
        ├── combined_class_best_model.joblib
        ├── food_type_best_model.joblib
        └── freshness_best_model.joblib

The new CSV must use the same sensor-column format as the training CSVs.

Outputs
-------
classification_outputs/test_outputs/
├── test_window_predictions.csv
└── test_overall_prediction.json
"""

from __future__ import annotations

import json
import math
import re
from collections import Counter
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd


# =============================================================================
# User setting: change this filename to the CSV you want to test
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent

TEST_CSV = BASE_DIR / "enose_test.csv"

CLASSIFICATION_DIR = BASE_DIR / "classification_outputs"
MODEL_DIR = CLASSIFICATION_DIR / "models"

METADATA_FILE = (
    CLASSIFICATION_DIR
    / "dataset_and_preprocessing_metadata.json"
)

MODEL_FILES = {
    "combined_class": (
        MODEL_DIR / "combined_class_best_model.joblib"
    ),
    "food_type": (
        MODEL_DIR / "food_type_best_model.joblib"
    ),
    "freshness": (
        MODEL_DIR / "freshness_best_model.joblib"
    ),
}

TEST_OUTPUT_DIR = CLASSIFICATION_DIR / "test_outputs"
WINDOW_OUTPUT_FILE = (
    TEST_OUTPUT_DIR / "test_window_predictions.csv"
)
SUMMARY_OUTPUT_FILE = (
    TEST_OUTPUT_DIR / "test_overall_prediction.json"
)

STATUS_COLUMNS = [
    "ads7828_ok",
    "nh3_ok",
    "h2s_ok",
]


# =============================================================================
# CSV loading and preprocessing
# =============================================================================

def parse_bool_series(series: pd.Series) -> pd.Series:
    if pd.api.types.is_bool_dtype(series):
        return series.fillna(False)

    values = (
        series.astype(str)
        .str.strip()
        .str.lower()
    )

    return values.isin(
        {"true", "1", "yes", "ok"}
    )


def read_test_csv(path: Path) -> pd.DataFrame:
    if not path.is_file():
        raise FileNotFoundError(
            f"Cannot find test CSV:\n{path}\n\n"
            "Change TEST_CSV at the top of test_model.py, or rename "
            "your new measurement file to enose_test.csv."
        )

    frame = pd.read_csv(path)

    if frame.empty:
        raise ValueError(
            f"Test CSV is empty: {path}"
        )

    if "timestamp_utc" in frame.columns:
        frame["timestamp_utc"] = pd.to_datetime(
            frame["timestamp_utc"],
            utc=True,
            errors="coerce",
        )
        frame = frame.sort_values(
            "timestamp_utc"
        )

    return frame.reset_index(drop=True)


def filter_valid_rows(
    raw_frame: pd.DataFrame,
    selected_channels: dict[str, str],
) -> pd.DataFrame:
    missing_columns = [
        source_column
        for source_column in selected_channels.values()
        if source_column not in raw_frame.columns
    ]

    if missing_columns:
        raise ValueError(
            "The test CSV is missing sensor column(s):\n"
            + "\n".join(missing_columns)
        )

    valid_mask = pd.Series(
        True,
        index=raw_frame.index,
    )

    for status_column in STATUS_COLUMNS:
        if status_column in raw_frame.columns:
            valid_mask &= parse_bool_series(
                raw_frame[status_column]
            )

    cleaned = pd.DataFrame(
        index=raw_frame.index
    )

    for sensor_name, source_column in (
        selected_channels.items()
    ):
        cleaned[sensor_name] = pd.to_numeric(
            raw_frame[source_column],
            errors="coerce",
        )

    valid_mask &= cleaned.notna().all(axis=1)

    if "timestamp_utc" in raw_frame.columns:
        cleaned.insert(
            0,
            "timestamp_utc",
            raw_frame["timestamp_utc"],
        )

    if "elapsed_s" in raw_frame.columns:
        insert_position = (
            1
            if "timestamp_utc" in cleaned.columns
            else 0
        )
        cleaned.insert(
            insert_position,
            "elapsed_s",
            pd.to_numeric(
                raw_frame["elapsed_s"],
                errors="coerce",
            ),
        )

    cleaned = cleaned.loc[
        valid_mask
    ].reset_index(drop=True)

    if cleaned.empty:
        raise ValueError(
            "No valid rows remain after checking status flags "
            "and missing sensor values."
        )

    return cleaned


def normalize_sensor_frame(
    clean_frame: pd.DataFrame,
    baseline_means: dict[str, float],
    baseline_scales: dict[str, float],
) -> pd.DataFrame:
    normalized = clean_frame.copy()

    metadata_columns = {
        "timestamp_utc",
        "elapsed_s",
    }

    for column in normalized.columns:
        if column in metadata_columns:
            continue

        if column not in baseline_means:
            raise ValueError(
                f"Missing baseline mean for channel: {column}"
            )

        if column not in baseline_scales:
            raise ValueError(
                f"Missing baseline scale for channel: {column}"
            )

        scale = float(
            baseline_scales[column]
        )

        if not math.isfinite(scale) or scale <= 0:
            raise ValueError(
                f"Invalid baseline scale for channel "
                f"{column}: {scale}"
            )

        normalized[column] = (
            normalized[column].astype(float)
            - float(baseline_means[column])
        ) / scale

    return normalized


# =============================================================================
# Feature extraction
# This must remain identical to the training code.
# =============================================================================

def safe_name(value: str) -> str:
    return re.sub(
        r"[^a-zA-Z0-9_]+",
        "_",
        value,
    ).strip("_").lower()


def safe_auc(values: np.ndarray) -> float:
    if hasattr(np, "trapezoid"):
        return float(
            np.trapezoid(values)
        )

    return float(np.trapz(values))


def safe_correlation(
    first: np.ndarray,
    second: np.ndarray,
) -> float:
    if len(first) < 2:
        return 0.0

    if (
        np.std(first) < 1e-12
        or np.std(second) < 1e-12
    ):
        return 0.0

    value = float(
        np.corrcoef(first, second)[0, 1]
    )

    return (
        value
        if math.isfinite(value)
        else 0.0
    )


def extract_features_from_window(
    window: pd.DataFrame,
    sensor_names: list[str],
) -> dict[str, float]:
    features: dict[str, float] = {}
    x_axis = np.arange(
        len(window),
        dtype=float,
    )

    for sensor_name in sensor_names:
        values = window[
            sensor_name
        ].to_numpy(dtype=float)

        prefix = safe_name(sensor_name)

        features[f"{prefix}_mean"] = float(
            np.mean(values)
        )
        features[f"{prefix}_std"] = float(
            np.std(values, ddof=0)
        )
        features[f"{prefix}_min"] = float(
            np.min(values)
        )
        features[f"{prefix}_max"] = float(
            np.max(values)
        )
        features[f"{prefix}_median"] = float(
            np.median(values)
        )
        features[f"{prefix}_q25"] = float(
            np.quantile(values, 0.25)
        )
        features[f"{prefix}_q75"] = float(
            np.quantile(values, 0.75)
        )
        features[f"{prefix}_range"] = float(
            np.max(values)
            - np.min(values)
        )
        features[
            f"{prefix}_last_minus_first"
        ] = float(
            values[-1] - values[0]
        )
        features[f"{prefix}_auc"] = (
            safe_auc(values)
        )
        features[f"{prefix}_slope"] = float(
            np.polyfit(
                x_axis,
                values,
                1,
            )[0]
        )

    for first_index in range(
        len(sensor_names)
    ):
        for second_index in range(
            first_index + 1,
            len(sensor_names),
        ):
            first_name = (
                sensor_names[first_index]
            )
            second_name = (
                sensor_names[second_index]
            )

            feature_name = (
                f"corr_{safe_name(first_name)}_"
                f"{safe_name(second_name)}"
            )

            features[feature_name] = (
                safe_correlation(
                    window[
                        first_name
                    ].to_numpy(dtype=float),
                    window[
                        second_name
                    ].to_numpy(dtype=float),
                )
            )

    tgs_names = [
        sensor_name
        for sensor_name in sensor_names
        if sensor_name.startswith("tgs")
    ]

    if tgs_names:
        tgs_window_means = np.array(
            [
                float(
                    window[
                        sensor_name
                    ].mean()
                )
                for sensor_name in tgs_names
            ],
            dtype=float,
        )

        features["tgs_array_mean"] = float(
            np.mean(tgs_window_means)
        )
        features[
            "tgs_array_std_between_sensors"
        ] = float(
            np.std(
                tgs_window_means,
                ddof=0,
            )
        )
        features[
            "tgs_array_range_between_sensors"
        ] = float(
            np.max(tgs_window_means)
            - np.min(tgs_window_means)
        )

    if (
        "nh3" in sensor_names
        and "h2s" in sensor_names
    ):
        features[
            "nh3_minus_h2s_mean"
        ] = float(
            window["nh3"].mean()
            - window["h2s"].mean()
        )

    return features


def create_test_windows(
    normalized_frame: pd.DataFrame,
    sensor_names: list[str],
    window_size: int,
    window_stride: int,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    if len(normalized_frame) < window_size:
        raise ValueError(
            f"Test CSV has only {len(normalized_frame)} valid rows, "
            f"but the trained model requires at least "
            f"{window_size} rows."
        )

    feature_rows: list[dict[str, float]] = []
    window_metadata: list[dict[str, Any]] = []

    for start in range(
        0,
        len(normalized_frame)
        - window_size
        + 1,
        window_stride,
    ):
        stop = start + window_size
        window = normalized_frame.iloc[
            start:stop
        ]

        feature_rows.append(
            extract_features_from_window(
                window,
                sensor_names,
            )
        )

        metadata_row: dict[str, Any] = {
            "window_index": len(
                window_metadata
            ),
            "window_start_row": start,
            "window_end_row": stop - 1,
        }

        if (
            "timestamp_utc"
            in normalized_frame.columns
        ):
            start_timestamp = (
                normalized_frame.iloc[
                    start
                ]["timestamp_utc"]
            )
            end_timestamp = (
                normalized_frame.iloc[
                    stop - 1
                ]["timestamp_utc"]
            )

            metadata_row[
                "window_start_timestamp"
            ] = str(start_timestamp)
            metadata_row[
                "window_end_timestamp"
            ] = str(end_timestamp)

        if (
            "elapsed_s"
            in normalized_frame.columns
        ):
            metadata_row[
                "window_start_elapsed_s"
            ] = float(
                normalized_frame.iloc[
                    start
                ]["elapsed_s"]
            )
            metadata_row[
                "window_end_elapsed_s"
            ] = float(
                normalized_frame.iloc[
                    stop - 1
                ]["elapsed_s"]
            )

        window_metadata.append(
            metadata_row
        )

    return (
        pd.DataFrame(feature_rows),
        pd.DataFrame(window_metadata),
    )


# =============================================================================
# Model loading and prediction
# =============================================================================

def load_training_metadata() -> dict[str, Any]:
    if not METADATA_FILE.is_file():
        raise FileNotFoundError(
            f"Cannot find training metadata:\n"
            f"{METADATA_FILE}\n\n"
            "Run food_freshness_multitask.py first."
        )

    return json.loads(
        METADATA_FILE.read_text(
            encoding="utf-8"
        )
    )


def load_model_package(
    task_name: str,
) -> dict[str, Any]:
    model_path = MODEL_FILES[task_name]

    if not model_path.is_file():
        raise FileNotFoundError(
            f"Cannot find model for {task_name}:\n"
            f"{model_path}\n\n"
            "Run food_freshness_multitask.py first."
        )

    package = joblib.load(model_path)

    required_keys = {
        "task_name",
        "model_name",
        "model",
        "feature_columns",
        "classes",
        "window_size",
        "window_stride",
    }

    missing_keys = (
        required_keys - set(package)
    )

    if missing_keys:
        raise ValueError(
            f"{model_path.name} is missing "
            f"required key(s): "
            f"{sorted(missing_keys)}"
        )

    return package


def predict_one_task(
    task_name: str,
    model_package: dict[str, Any],
    feature_frame: pd.DataFrame,
) -> tuple[
    dict[str, Any],
    pd.DataFrame,
]:
    model = model_package["model"]
    feature_columns = list(
        model_package["feature_columns"]
    )

    missing_features = [
        feature
        for feature in feature_columns
        if feature not in feature_frame.columns
    ]

    if missing_features:
        raise ValueError(
            f"Test features for task {task_name} "
            f"are missing:\n"
            + "\n".join(
                missing_features
            )
        )

    model_input = feature_frame.reindex(
        columns=feature_columns
    )

    predicted_labels = model.predict(
        model_input
    )

    prediction_table = pd.DataFrame(
        {
            f"{task_name}_prediction": (
                predicted_labels
            ),
        }
    )

    overall_label: str
    confidence: float
    class_scores: dict[str, float]

    if hasattr(model, "predict_proba"):
        probabilities = model.predict_proba(
            model_input
        )

        class_names = [
            str(value)
            for value in model.classes_
        ]

        mean_probabilities = (
            probabilities.mean(axis=0)
        )

        best_index = int(
            np.argmax(mean_probabilities)
        )

        overall_label = class_names[
            best_index
        ]
        confidence = float(
            mean_probabilities[best_index]
        )

        class_scores = {
            class_name: float(
                mean_probabilities[index]
            )
            for index, class_name
            in enumerate(class_names)
        }

        for index, class_name in enumerate(
            class_names
        ):
            prediction_table[
                f"{task_name}_probability_"
                f"{safe_name(class_name)}"
            ] = probabilities[:, index]

        aggregation_method = (
            "mean_window_probability"
        )

    else:
        counts = Counter(
            str(value)
            for value in predicted_labels
        )

        overall_label, winning_count = (
            counts.most_common(1)[0]
        )

        confidence = (
            winning_count
            / len(predicted_labels)
        )

        class_scores = {
            class_name: (
                count
                / len(predicted_labels)
            )
            for class_name, count
            in counts.items()
        }

        aggregation_method = (
            "majority_window_vote"
        )

    summary = {
        "task": task_name,
        "model_name": str(
            model_package["model_name"]
        ),
        "overall_prediction": (
            overall_label
        ),
        "confidence": confidence,
        "aggregation_method": (
            aggregation_method
        ),
        "window_count": len(
            predicted_labels
        ),
        "class_scores": class_scores,
    }

    return summary, prediction_table


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    print("E-nose model test")
    print("=" * 72)
    print(f"Test CSV: {TEST_CSV.resolve()}")

    training_metadata = (
        load_training_metadata()
    )

    selected_channels = dict(
        training_metadata[
            "selected_channels"
        ]
    )
    baseline_means = {
        key: float(value)
        for key, value in training_metadata[
            "baseline_means"
        ].items()
    }
    baseline_scales = {
        key: float(value)
        for key, value in training_metadata[
            "baseline_scales"
        ].items()
    }

    model_packages = {
        task_name: load_model_package(
            task_name
        )
        for task_name in MODEL_FILES
    }

    window_sizes = {
        int(package["window_size"])
        for package in (
            model_packages.values()
        )
    }
    window_strides = {
        int(package["window_stride"])
        for package in (
            model_packages.values()
        )
    }

    if len(window_sizes) != 1:
        raise ValueError(
            "The three models use different "
            "window sizes."
        )

    if len(window_strides) != 1:
        raise ValueError(
            "The three models use different "
            "window strides."
        )

    window_size = window_sizes.pop()
    window_stride = (
        window_strides.pop()
    )

    raw_frame = read_test_csv(TEST_CSV)
    clean_frame = filter_valid_rows(
        raw_frame,
        selected_channels,
    )
    normalized_frame = (
        normalize_sensor_frame(
            clean_frame,
            baseline_means,
            baseline_scales,
        )
    )

    sensor_names = list(
        selected_channels
    )

    feature_frame, window_metadata = (
        create_test_windows(
            normalized_frame,
            sensor_names,
            window_size,
            window_stride,
        )
    )

    print("\nPreprocessing summary")
    print("-" * 72)
    print(
        f"Raw rows:          "
        f"{len(raw_frame)}"
    )
    print(
        f"Valid rows:        "
        f"{len(clean_frame)}"
    )
    print(
        f"Selected channels: "
        f"{sensor_names}"
    )
    print(
        f"Window size:       "
        f"{window_size}"
    )
    print(
        f"Window stride:     "
        f"{window_stride}"
    )
    print(
        f"Test windows:      "
        f"{len(feature_frame)}"
    )

    combined_window_output = (
        window_metadata.copy()
    )
    overall_results: dict[
        str,
        Any,
    ] = {
        "test_csv": str(
            TEST_CSV.resolve()
        ),
        "raw_rows": len(raw_frame),
        "valid_rows": len(clean_frame),
        "window_count": len(
            feature_frame
        ),
        "selected_channels": (
            selected_channels
        ),
        "predictions": {},
    }

    print("\nPredictions")
    print("=" * 72)

    for task_name in [
        "food_type",
        "freshness",
        "combined_class",
    ]:
        summary, task_window_output = (
            predict_one_task(
                task_name,
                model_packages[task_name],
                feature_frame,
            )
        )

        overall_results[
            "predictions"
        ][task_name] = summary

        combined_window_output = pd.concat(
            [
                combined_window_output,
                task_window_output,
            ],
            axis=1,
        )

        print(
            f"\nTask: {task_name}"
        )
        print(
            f"Model: "
            f"{summary['model_name']}"
        )
        print(
            f"Prediction: "
            f"{summary['overall_prediction']}"
        )
        print(
            f"Confidence: "
            f"{summary['confidence']:.4f}"
        )

        for class_name, score in (
            summary[
                "class_scores"
            ].items()
        ):
            print(
                f"  {class_name}: "
                f"{score:.4f}"
            )

    TEST_OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    combined_window_output.to_csv(
        WINDOW_OUTPUT_FILE,
        index=False,
    )

    SUMMARY_OUTPUT_FILE.write_text(
        json.dumps(
            overall_results,
            indent=2,
        ),
        encoding="utf-8",
    )

    print("\nSaved outputs")
    print("=" * 72)
    print(
        f"Window predictions:\n"
        f"  {WINDOW_OUTPUT_FILE.resolve()}"
    )
    print(
        f"Overall prediction:\n"
        f"  {SUMMARY_OUTPUT_FILE.resolve()}"
    )

    combined_prediction = (
        overall_results[
            "predictions"
        ]["combined_class"][
            "overall_prediction"
        ]
    )
    food_prediction = (
        overall_results[
            "predictions"
        ]["food_type"][
            "overall_prediction"
        ]
    )
    freshness_prediction = (
        overall_results[
            "predictions"
        ]["freshness"][
            "overall_prediction"
        ]
    )

    print("\nFinal result")
    print("=" * 72)
    print(
        f"Food type:      "
        f"{food_prediction}"
    )
    print(
        f"Freshness:      "
        f"{freshness_prediction}"
    )
    print(
        f"Combined class: "
        f"{combined_prediction}"
    )

    expected_combined = (
        f"{freshness_prediction}_"
        f"{food_prediction}"
    )

    if (
        combined_prediction
        != expected_combined
    ):
        print(
            "\nConsistency warning:"
        )
        print(
            "The combined-class model does not "
            "agree with the separate food-type "
            "and freshness models."
        )
        print(
            f"Separate predictions imply: "
            f"{expected_combined}"
        )


if __name__ == "__main__":
    try:
        main()
    except Exception as error:
        print("\nERROR")
        print("=" * 72)
        print(error)
        raise
